### ISSUE TITLE
TypeError: slice indices must be integers or None or have an __index__ method

### ISSUE THREAD

**Issue by isilayy** [kcmahip/opencv-eye-tracking#1]
I have a problem :  frame[y + (h * .25):(y + h), x:(x + w)])  # using histogram equalization of better image.
TypeError: slice indices must be integers or None or have an __index__ method

What is the solution?

**Comment by kcmahip** [comment]
Is this resolved? @isilayy

**Comment by isilayy** [comment]
No not solved yet

**Comment by kcmahip** [comment]
Latest merge pull request #3  resolves this.  @isilayy
